### ISSUE TITLE
Publish latest changes to npm

### ISSUE THREAD

**Issue by meandavejustice** [doowb/accountdown-token#3]
Would you mind bumping the version # and publishing to npm with the latest dep changes?

**Comment by doowb** [comment]
Done. Just wanted to updated a few other things (readme and dotfiles). Published as 0.1.2.

**Comment by meandavejustice** [comment]
Thanks! sorry if that sounded pushy :)

**Comment by doowb** [comment]
np, btw... I'm interested in hearing how you're using this. I had originally created it to be used with short lived tokens, like email verification tokens, but also thought that it's useful for longer lived tokens like API tokens. If you have any thoughts, I'd like to hear them.

**Comment by meandavejustice** [comment]
I'm using this for both email verification tokens and longer lived tokens. Kind of rolling my own version of http://passwordless.net/ for a little newsletter signup. The source will be [here](https://github.com/meandavejustice/pdx-activist-newsletter)

So basically the flow is:
- `signup/{email}` generates temp validation token, which i email to the user.
- `confirm/{email}/{token}` validates token hasn't expired, generates new token and updates record. and sets cookie which will be used for login.

Then the user should be logged in. If there are any issues they will be prompted to signin again using the same method.

**Comment by doowb** [comment]
Makes sense. It's like 2-factor authentication but only when someone "loses" their original token (either by a cookie expiring, clearing cookies, or logging in on another device). Let me know if you run into any problems.
